### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Grimfoxy19883** [riffy-team/riffy-music-bot#2]
TypeError: command.run is not a function
    at Client.<anonymous> (/home/container/structures/events/client/interactionCreate.js:87:23)
    at Client.emit (node:events:525:35)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/home/container/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
    at WebSocketShard.<anonymous> (/home/container/node_modules/@discordjs/ws/dist/index.js:1173:51)
    at WebSocketShard.emit (/home/container/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
    at WebSocketShard.onMessage (/home/container/node_modules/@discordjs/ws/dist/index.js:988:14)

**Comment by Elitex07** [comment]
@Grimfoxy19883 Is it coming from a command, which you have added externally?

**Comment by Grimfoxy19883** [comment]
nvm i Found the issue and to answer your question yes it was...

**Comment by Grimfoxy19883** [comment]
although i got one question how do i make youtube links and spotiFy links work in soundcloud

**Comment by Grimfoxy19883** [comment]
like how do i make youtube links and spotiFy work with     defaultSearchPlatform: "scsearch",
