### ISSUE TITLE
ERROR CODE MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Numdiggg** [riffy-team/riffy-music-bot#3]
Require stack:
- E:\riffy-music-bot\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (E:\riffy-music-bot\index.js:27:5)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'E:\\riffy-music-bot\\index.js' ]
}

Node.js v21.6.1
PS E:\riffy-music-bot>

**Comment by UnschooledGamer** [comment]
> Require stack:
> 
> * E:\riffy-music-bot\index.js
>   at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
>   at Module._load (node:internal/modules/cjs/loader:990:27)
>   at Module.require (node:internal/modules/cjs/loader:1237:19)
>   at require (node:internal/modules/helpers:176:18)
>   at Object. (E:\riffy-music-bot\index.js:27:5)
>   at Module._compile (node:internal/modules/cjs/loader:1378:14)
>   at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
>   at Module.load (node:internal/modules/cjs/loader:1212:32)
>   at Module._load (node:internal/modules/cjs/loader:1028:12)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ 'E:\riffy-music-bot\index.js' ]
>   }
> 
> Node.js v21.6.1 PS E:\riffy-music-bot>

`index.js` is present in the root directory of riffy-music-bot possibly you have not pulled/downloaded the latest files.
