### ISSUE TITLE
Error: You have to initialize Riffy in your ready event

### ISSUE THREAD

**Issue by PureeThunder** [riffy-team/riffy-music-bot#5]
`[2024-06-30 14:23:11]: An error occurred while processing a slash command:
Error: You have to initialize Riffy in your ready event
    at Riffy.createConnection (/home/container/node_modules/riffy/build/structures/Riffy.js:95:36)
    at Object.run (/home/container/sleepy/sleepy/structures/slashcommands/music/play.js:27:37)
    at Client.<anonymous> (/home/container/sleepy/sleepy/structures/events/client/interactionCreate.js:84:23)
    at Client.emit (node:events:525:35)
    at InteractionCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
    at WebSocketManager.emit (/home/container/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:285:31)
    at WebSocketShard.<anonymous> (/home/container/node_modules/@discordjs/ws/dist/index.js:1190:51)`

**Comment by blad3fear** [comment]
Just type `client.riffy.init(client.user.id)` in your ready event file or in your client.on("ready")
